### PR TITLE
fix(middleware-user-agent): use retry strategy mode property instead of legacy fallback

### LINKED ISSUE #7574: feature attribution for retry mode should not include "legacy"
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

in user agent `check-features.ts` file, the detection of pre-SRA retries should not attribute the retry as "legacy" mode. It should differentiate and set the feature as either (pre-SRA) standard or (pre-SRA) adaptive. 

Legacy refers to the retry behavior in AWS SDK JSv2, which does not exist in this SDK.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.669.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

any

### Reproduction Steps

make a request with pre-SRA retries and inspect the user agent feature metadata

### Observed Behavior

it contains D for legacy

### Expected Behavior

it should contain either F or E for adaptive/standard.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### PR DESCRIPTION
**Pull request by TrevorBurnham**
Fixes #7574

### Problem

The `checkFeatures` function in `middleware-user-agent` incorrectly attributes pre-SRA retry strategies as "legacy" (`D`) in the user-agent feature metadata. It does this by checking for `acquireInitialRetryToken` (a `RetryStrategyV2`-only method), and if absent, assumes the retry mode is legacy.

"Legacy" refers to AWS SDK for JavaScript v2 retry behavior, which does not exist in v3. Pre-SRA retry strategies in this SDK are still either standard or adaptive — they just implement the older `RetryStrategy` interface instead of `RetryStrategyV2`.

### Solution

All retry strategies in v3 (both SRA and pre-SRA) expose a `mode` property set to either `"standard"` or `"adaptive"`. The fix replaces the `acquireInitialRetryToken` type-check branching with a single `mode` property check, which correctly identifies the retry mode regardless of which interface the strategy implements.

Before:
```ts
if (typeof (retryStrategy as RetryStrategyV2).acquireInitialRetryToken === "function") {
  if (retryStrategy.constructor?.name?.includes("Adaptive")) {
    setFeature(context, "RETRY_MODE_ADAPTIVE", "F");
  } else {
    setFeature(context, "RETRY_MODE_STANDARD", "E");
  }
} else {
  setFeature(context, "RETRY_MODE_LEGACY", "D"); // wrong for v3 pre-SRA strategies
}
```

After:
```ts
if (typeof retryStrategy.mode === "string" && retryStrategy.mode.includes("adaptive")) {
  setFeature(context, "RETRY_MODE_ADAPTIVE", "F");
} else {
  setFeature(context, "RETRY_MODE_STANDARD", "E");
}
```

### Checklist
- [ ] If the PR is a feature, add integration tests (`*.integ.spec.ts`) or E2E tests.
  - [x] It's not a feature.
- [ ] My E2E tests are resilient to concurrent i/o.
  - [x] I didn't write any E2E tests.
- [ ] I added access level annotations e.g. `@public`, `@internal` tags and enabled doc generation on the package. Remember that access level annotations go below the description, not above.
  - [x] I didn't add any public functions.
- [ ] Streams - how do they work?? My WebStream readers/locks are properly lifecycled. Node.js stream backpressure is handled. Error handling.
  - [x] No streams here.

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: packages-internal/middleware-user-agent/src/check-features.ts [hunk 1]
```diff
@@ -46,14 +40,10 @@ export async function checkFeatures(
...
-        setFeature(context, "RETRY_MODE_ADAPTIVE", "F");
-      } else {
-        setFeature(context, "RETRY_MODE_STANDARD", "E");
-      }
+    if (typeof retryStrategy.mode === "string" && retryStrategy.mode.includes("adaptive")) {
+      setFeature(context, "RETRY_MODE_ADAPTIVE", "F");
     } else {
-      setFeature(context, "RETRY_MODE_LEGACY", "D");
+      setFeature(context, "RETRY_MODE_STANDARD", "E");
     }
```
Comment (trivikr) [inline packages-internal/middleware-user-agent/src/check-features.ts]: We should do exact match for values from util-retry, and skip logging otherwise.
```suggestion
    if (typeof retryStrategy.mode === "string") {
      switch (retryStrategy.mode) {
        case RETRY_MODES.ADAPTIVE:
          setFeature(context, "RETRY_MODE_ADAPTIVE", "F");
          break;
        case RETRY_MODES.STANDARD:
          setFeature(context, "RETRY_MODE_STANDARD", "E");
          break;
      }
    }
```

where
```js
import { RETRY_MODES } from "@smithy/util-retry";
```

Comment (TrevorBurnham) [reply packages-internal/middleware-user-agent/src/check-features.ts]: Updated!

File: packages-internal/middleware-user-agent/package.json [hunk 2]
```diff
@@ -31,6 +31,7 @@
     "@smithy/core": "^3.23.8",
     "@smithy/protocol-http": "^5.3.11",
     "@smithy/types": "^4.13.0",
+    "@smithy/util-retry": "^4.2.10",
```
Comment (trivikr) [inline packages-internal/middleware-user-agent/package.json]: The version was updated this morning.
```suggestion
    "@smithy/util-retry": "^4.2.11",
```

Can you rebase from main and also run `yarn` to update lockfile?
And push with `--force-with-lease`?

Comment (TrevorBurnham) [reply packages-internal/middleware-user-agent/package.json]: Done!
