### PR TITLE
fix: multiple XML collection deserialization bugs

### LINKED ISSUE #765: iam.createUser fails with TypeError "Cannot read property 'member' of undefined"
**Describe the bug**
iam.createUser doesn't create user

**SDK version number**
```console
$ yarn list aws-sdk
└─ aws-sdk@2.605.0
$ yarn list @aws-sdk/client-iam
└─ @aws-sdk/client-iam@1.0.0-alpha.2
```

**Is the issue in the browser/Node.js?**
Node.js

**Details of the browser/Node.js version**
v12.14.0

**To Reproduce (observed behavior)**
Reproduced with the following code:
```javascript
const AWS = require("aws-sdk");
const { IAM } = require("@aws-sdk/client-iam");

(async () => {
  let response;
  const region = "us-west-2";
  const UserName =
    "test-user-" +
    Math.random()
      .toString(36)
      .substring(2, 15);

  const v2Client = new AWS.IAM({ region });
  response = await v2Client.createUser({ UserName }).promise();
  console.log("Data returned by v2:");
  console.log(response);
  await v2Client.waitFor("userExists", { UserName }).promise();
  await v2Client.deleteUser({ UserName }).promise();

  const v3Client = new IAM({ region });
  try {
    await v3Client.createUser({ UserName });
  } catch (e) {
    console.log("\nError returned by v3:");
    console.log(e);
  }
})();
```

Output:
```console
Data returned by v2:
{
  ResponseMetadata: { RequestId: 'e0b645a3-6c3f-4208-bc8c-48966258f45f' },
  User: {
    Path: '/',
    UserName: 'test-user-c105b0nx29m',
    UserId: 'AIDA5ROEOH3WFYCUZYQ7N',
    Arn: 'arn:aws:iam::930809265900:user/test-user-c105b0nx29m',
    CreateDate: 2020-01-21T00:59:20.000Z,
    Tags: []
  }
}

Error returned by v3:
TypeError: Cannot read property 'member' of undefined
    at deserializeAws_queryUser (/Users/trivikr/workspace/AwsJavaScriptSdkIntegTests/node_modules/@aws-sdk/client-iam/dist/cjs/protocols/Aws_query.js:10792:23)
    at deserializeAws_queryCreateUserResponse (/Users/trivikr/workspace/AwsJavaScriptSdkIntegTests/node_modules/@aws-sdk/client-iam/dist/cjs/protocols/Aws_query.js:8449:25)
    at Object.deserializeAws_queryCreateUserCommand (/Users/trivikr/workspace/AwsJavaScriptSdkIntegTests/node_modules/@aws-sdk/client-iam/dist/cjs/protocols/Aws_query.js:2036:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  '$metadata': { retries: 0, totalRetryDelay: 0 }
}
```

**Expected behavior**
iam.createUser should create user ([docs](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IAM.html#createUser-property))

### PR DESCRIPTION
**Pull request by kstich**
This commit fixes a couple issues with generating code to deserialize
structure, union, or body members that target collection members.

1. Unflattened shapes that could return multiple entries in their
collection but only return one would result in an error at runtime
trying to iterate over an object like it was an Array.
2. Unflattened shapes that were not set in the provided output would
result in an error at runtime when trying to validate the entry exists
element without validating that its parent element existed.

This update also bumps the version of smithy-aws-traits to latest.

Fixes #765 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java [hunk 1]
```diff
@@ -99,17 +103,23 @@ protected void deserializeStructure(GenerationContext context, StructureShape sh
...
+            deserializeNamedMember(context, memberName, memberShape, () -> "output", (dataSource, visitor) -> {
+                writer.write("contents.$L = $L;", memberName, target.accept(visitor));
+            });
+        });
 
         writer.write("return contents;");
     }
 
-    void deserializeNamedStructureMember(
+    void deserializeNamedMember(
```
Comment (mtdowling) [inline codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/XmlShapeDeserVisitor.java]: This method is getting hairy, so even though it's package private, documentation is probably required at this point.
