### PR TITLE
fix: bump up tslib to 2.3.0

### LINKED ISSUE #2582: TypeError when creating new CognitoIdentityClient
## Describe the bug
I am trying to create an S3Client object in my NodeJS service that will use credentials from my Cognito Identity Pool. I've followed the tutorial here: https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/loading-browser-credentials-cognito.html. However, when I run that code, I see `TypeError: Object(...) is not a function`.

It comes from the `new CognitoIdentityClient({region: REGION})` line.

The stack trace:
```
TypeError: Object(...) is not a function
    at defaultProvider (...)
    at Object.credentialDefaultProvider (...)
    at resolveAwsAuthConfig (...)
    at new CognitoIdentityClient (...)
```

## Your environment
macOS Catalina v10.15.7, MacBook Pro (16-inch, 2019)

Running this inside the WebStorm IDE from JetBrains.

#### SDK version number
```
"@aws-sdk/client-cognito-identity": "^3.20.0",
"@aws-sdk/client-s3": "^3.20.0",
"@aws-sdk/credential-provider-cognito-identity": "^3.20.0",
````

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
```
node -v
v12.19.1
```

## Steps to reproduce
```
const {S3Client} = require("@aws-sdk/client-s3");
const {CognitoIdentityClient} = require("@aws-sdk/client-cognito-identity");
const {fromCognitoIdentityPool} = require("@aws-sdk/credential-provider-cognito-identity");

// AWS Constants
const REGION = 'us-east-1';
const IDENTITY_POOL_ID = 'IDENTITY_POOL_ID'; // removing actual ID
const USER_POOL_ID = 'USER_POOL_ID'; //removing actual ID
const COGNITO_ID = `cognito-idp.${REGION}.amazonaws.com/${USER_POOL_ID}`;

export async function listS3Files(token) {
    try {
        const loginData = {
            [COGNITO_ID]: token
        };
        const s3Client = new S3Client({
            region: REGION,
            credentials: fromCognitoIdentityPool({
                client: new CognitoIdentityClient({region: REGION}),
                identityPoolId: IDENTITY_POOL_ID,
                logins: {
                    ...loginData
                }
            })
        });
    } catch (error) {
        console.log(error);
        throw error;
    }
}

```

#### Observed behavior
Trying to create an S3Client using the v3 tutorial results in a TypeError being thrown when the CognitoIdentityClient is created.

#### Expected behavior
No TypeError should be thrown. I should be able to create the S3Client with no issues.

### LINKED ISSUE #2587: Unable to get configuration from AppConfig on browser
## Describe the bug
`@aws-sdk/client-appconfig` is referencing `tslib@2.0.0` and that package does not implement `__spreadArray`. When loading the package on a React app I see the following warnings
```
"export '__spreadArray' was not found in 'tslib'
```
I am not able to fetch the App Configs

#### SDK version number
`@aws-sdk/client-appconfig@3.21.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
```
Chrome: 91.0.4472.164
node -v
v10.22.0
```
## Steps to reproduce
```javascript
export const getAppConfigs = async (
  code: String,
): Object => {
  try {
    const Client = new AppConfigClient({
      region: <REGION>,
      credentials: {
        accessKeyId: <ACCESS_KEY>,
        secretAccessKey: <SECRET_KEY>
      }
    });
    const command = new GetConfigurationCommand({
      Application: `App-${code}`,
      ClientId: `App-${code}-Client`,
      Configuration: "AppConfig",
      Environment: "Dev"
    });
    const response = await Client.send(command); // Fails here
    let parsedConfigs = JSON.parse(
      String.fromCharCode.apply(null, response.Content)
    );

  } catch (error) {
    throw error;
  }
};
```
#### Observed behavior
When I send a request I get the following error
```
TypeError: Object(...) is not a function
    at MiddlewareStack.js:110
    at Array.reduce (<anonymous>)
    at getMiddlewareList (MiddlewareStack.js:108)
    at Object.resolve (MiddlewareStack.js:190)
    at GetConfigurationCommand../node_modules/@aws-sdk/client-appconfig/dist/es/commands/GetConfigurationCommand.js.GetConfigurationCommand.resolveMiddleware (GetConfigurationCommand.js:64)
    at AppConfigClient../node_modules/@aws-sdk/client-appconfig/node_modules/@aws-sdk/smithy-client/dist/es/client.js.Client.send (client.js:10)
    at _callee3$ (Auth.js:122)
```

#### Expected behavior
Expected to receive the AppConfig blob response.

#### Screenshots
According to browser dev tools the `MiddlewareStack.js:110` depends on `__spreadArray`
image

## Additional context
I replaced `tslib` from `@aws-sdk/client-appconfig@3.21.0` manually with version `tslib@2.3.0` and the following warning went away.
```
"export '__spreadArray' was not found in 'tslib'
```

However, the request kept on failing when trying to fetch the AppConfigs

### PR DESCRIPTION
**Pull request by AllanZhengYP**
### Issue
Resolves #2587 
Resolves #2582

### Description
* Bump up tslib version from `"^2.0.0"` to `^2.3.0`
* Add a CI test that will **fail** everytime we upgrade TypeScript version. It will bring attentions and make sure tslib version is bumped up at the same time.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AllanZhengYP** [comment]
CI is broken for ts-node:
```
error ts-node@10.1.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.23.0"
error Found incompatible module.
```

**Comment by AllanZhengYP** [comment]
Bumped the node.js in runtime from 10 to 12 to fix the issue

**Review by alexforsyth — APPROVED** [review]
+1

File: tests/versions/tslib.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
+/**
+ * Validate the tslib and tsc version is consistent and corresponds to each other.
+ */
+import { execSync } from "child_process";
+import { readFileSync } from "fs";
+import JSON from "json5";
```
Comment (trivikr) [inline tests/versions/tslib.ts:6]: Can we use [JSON.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse), and move comment from versions.json to the test code? This way we can avoid direct devDependency on `json5` package.

Another option is to use `_comment` key for comment as follows:
```json
{
  "_comment": "You need to make sure 'tslib' version is compatible with typescript version.",
  "tslib": "^2.3.0",
  "typescript": "~4.3.2"
}
```

File: package.json [hunk 2]
```diff
@@ -26,6 +26,7 @@
     "test:server-protocols": "yarn build:server-protocols && lerna run test --scope '@aws-sdk/*-server'",
     "pretest:e2e": "yarn build:crypto-dependencies && lerna run --scope '@aws-sdk/{client-cloudformation,karma-credential-loader}' --include-dependencies build",
     "test:e2e": "node ./tests/e2e/index.js",
+    "test:versions": "ts-node tests/versions/tslib.ts",
```
Comment (trivikr) [inline package.json:29]: Should `test:versions` be called on `test:all`, before unit tests are run?

File: tests/versions/tslib.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+type PackageInfo = {
+  name: string;
+  version: string;
+  private: boolean;
+  location: string;
+};
+
+console.log("Validating the tslib and tsc version is consistent within workspace.");
+const expectedVersions: { [name: string]: string } = JSON.parse(readFileSync(join(__dirname, "versions.json"), "utf8"));
+const packagesInfo: PackageInfo[] = JSON.parse(execSync("./node_modules/.bin/lerna list -l --json").toString());
```
Comment (trivikr) [inline tests/versions/tslib.ts:18]: Instead of calling lerna with execSync, should we call subdirectories of workspaces listed in root package.json?

That way, we won't have a dependency on lerna from the test code.

**Comment by trivikr** [comment]
The code change to upgrade tslib version looks good to me.
The `test:versions` be moved to a separate PR, as all my comments are related to it.

File: tests/versions/tslib.ts (hunk 1 above)
Comment (AllanZhengYP) [reply tests/versions/tslib.ts]: If you are worry of the dependency, JSON5 is already in our dependency graph. `"_comment"` does not draw as much attention as real comment either.

File: package.json (hunk 2 above)
Comment (AllanZhengYP) [reply package.json]: It's already included if I use`*.spec.ts` to name the file

**Review by trivikr — APPROVED** [review]
