### PR TITLE
fix(property-provider): memoize provider after the first evoke

### LINKED ISSUE #1466: v1.0.0-gamma.7 / #1420 causes `Region is missing` errors
**Describe the bug**

v1.0.0-gamma.7 and presumably https://github.com/aws/aws-sdk-js-v3/pull/1420 broke perfectly working S3 client implementation.

```
  console.error
    Error: Region is missing
        at default (/Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/config-resolver/src/RegionConfig.ts:12:4)
        at /Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/node-config-provider/src/fromStatic.ts:9:59
        at step (/Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:141:27)
        at Object.next (/Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:122:57)
        at /Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:115:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/Users/roderik/Development/bpaas-launchpad/node_modules/tslib/tslib.js:111:16)
        at /Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/node-config-provider/src/fromStatic.ts:9:56
        at /Users/roderik/Development/bpaas-launchpad/node_modules/@aws-sdk/node-config-provider/node_modules/@aws-sdk/property-provider/src/chain.ts:23:19

      at process.uncaught (../../node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Env.js:249:21)
      at processEmit [as emit] (../../node_modules/signal-exit/index.js:161:32)
```

Reverting back to gamma.6 makes these errors go away.

The code we use to initialize S3 is

```
export enum EKSRegion {
  EUROPE = 'eu-west-3',
  UNITED_STATES = 'us-east-2',
  INDIA = 'ap-south-1',
  SINGAPORE = 'ap-southeast-1',
}
```

```
    this.s3 = new S3({
      credentials: {
        accessKeyId: config.providers.EKS.accessKeyId,
        secretAccessKey: config.providers.EKS.secretAccessKey,
      },
      region: EKSRegion.EUROPE,
    });
```

**SDK version number**

v1.0.0-gamma.7

**Is the issue in the browser/Node.js/ReactNative?**

Node.js

**Details of the browser/Node.js/ReactNative version**

v14.7.0

### PR DESCRIPTION
**Pull request by AllanFly120**
Resolves #1466 

*Description of changes:*
This change makes the memoize function loads the value after the first invoke instead of immediately when calling `memoize()`.

Detailed root cause is stated in the original issue: https://github.com/aws/aws-sdk-js-v3/issues/1466#issuecomment-681147889. This issue was not caught because all of the environments we run CI, and developers machine, already has `AWS_REGION` value set. 

To prevent it happens again, we need to check and clean the environment of our CI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: packages/property-provider/src/memoize.ts [hunk 1]
```diff
@@ -43,16 +43,26 @@ export const memoize: MemoizeOverload = <T>(
...
+  let hasResult: boolean;
   if (isExpired === undefined) {
     // This is a static memoization; no need to incorporate refreshing
-    const result = provider();
-    return () => result;
+    return () => {
+      if (!hasResult) {
+        result = provider();
+        hasResult = true;
+      }
```
Comment (trivikr) [inline packages/property-provider/src/memoize.ts:54]: Remove usage of `hasResult` variable altogether?
```suggestion
      if (!result) {
        result = provider();
      }
```

Ditto on line 62-65

Comment (AllanFly120) [reply packages/property-provider/src/memoize.ts:54]: This is to catch the cases when result is `null` or `undefined` or `false`

**Comment by AllanFly120** [comment]
The retried build succeeds. [Link](https://us-west-2.console.aws.amazon.com/codesuite/codebuild/119327258862/projects/sdk-staging-test/build/sdk-staging-test%3Add9e734c-c1db-4bed-95a7-e51cbe6e48f9/?region=us-west-2) for build logs

**Comment by trivikr** [comment]
Ref: Original build failed because of issue https://github.com/aws/aws-sdk-js-v3/issues/1460
