### PR TITLE
fix(client-s3): disable bucket endpoint plugin in WriteGetObjectResponseCommand

### LINKED ISSUE #2476: WriteGetObjectResponseCommand issue
## Describe the bug

`WriteGetObjectResponseCommand` throw error when try to send command
LambdaResponseNotReceived: The Lambda exited without successfully calling WriteGetObjectResponse.

## Code example 

```
import { S3Client, S3 } from '@aws-sdk/client-s3';

 const s3Client = new S3Client({});

async function passTransformedPhoto(
  body: Buffer,
  outputRoute: string,
  outputToken: string,
): Promise<WriteGetObjectResponseCommandOutput> {
  try {
    const writeGetObjectParams: WriteGetObjectResponseCommandInput = {
      RequestRoute: outputRoute,
      RequestToken: outputToken,
      Body: body,
    };

    const command = new WriteGetObjectResponseCommand(writeGetObjectParams);
    console.log('s3Client send');

    const res = await s3Client.send(command);
    return res;
  } catch (e) {
    console.log('Error happens in passTransformedPhoto');
    console.log(e);
    return e;
  }
}
```

The same issue with the aggregated client

```
import { S3Client, S3 } from '@aws-sdk/client-s3';
 const s3Aggregated = new S3({});

async function passTransformedPhoto(body: Buffer, outputRoute: string, outputToken: string) {
  try {
    const result = await s3Aggregated.writeGetObjectResponse({
      RequestRoute: outputRoute,
      RequestToken: outputToken,
      Body: body,
    });
    return result;
  } catch (e) {
    console.log('Error happens in passTransformedPhoto');
    console.log(e);
    return e;
  }
}

```

## Output 

Error happens in passTransformedPhoto

```
INFO	TypeError: Cannot destructure property 'service' of 'bucketName' as it is undefined.
    at getEndpointFromArn (/var/task/node_modules/@aws-sdk/middleware-bucket-endpoint/dist/cjs/bucketHostname.js:26:13)
    at Object.bucketHostname (/var/task/node_modules/@aws-sdk/middleware-bucket-endpoint/dist/cjs/bucketHostname.js:17:13)
    at /var/task/node_modules/@aws-sdk/middleware-bucket-endpoint/dist/cjs/bucketEndpointMiddleware.js:47:67
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

## Expected result

bucketName should looks like this 

```
bucketName: {
    partition: 'aws',
    service: 's3-object-lambda',
    region: 'us-east-2',
    accountId: '11111111',
    resource: 'accesspoint/access-point'
  }

```

#### SDK version number
`@aws-sdk/client-s3": "^3.18.0"`
Node.js v 14.17.0
 "typescript": "^4.3.2",

### PR DESCRIPTION
**Pull request by AllanZhengYP**
### Issue
Resolves #2476

### Description
We have a customization that will inspect the S3 request’s `Bucket` parameters. This customization should only be applied to operations with `Bucket` input parameter. However, it was incorrectly applied to the operation which doesn’t have such parameter

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java [hunk 1]
```diff
@@ -178,14 +180,13 @@ public void addConfigInterfaceFields(TypeScriptSettings settings, Model model, S
...
-                        .operationPredicate((m, s, o) -> testInputContainsMember(m, o, SSEC_OPERATIONS)
+                        .operationPredicate((m, s, o) -> testInputContainsMember(m, o, SSEC_INPUT_KEYS)
                                             && testServiceId(s))
                         .build(),
                 RuntimeClientPlugin.builder()
                         .withConventions(AwsDependency.LOCATION_CONSTRAINT.dependency, "LocationConstraint",
                                          HAS_MIDDLEWARE)
-                        .operationPredicate((m, s, o) -> o.getId().getName(s).equals("CreateBucket")
-                                            && testServiceId(s))
+                        .operationPredicate((m, s, o) -> o.getId().getName(s).equals("CreateBucket") && testServiceId(s))
```
Comment (trivikr) [inline codegen/smithy-aws-typescript-codegen/src/main/java/software/amazon/smithy/aws/typescript/codegen/AddS3Config.java:189]: fix for checkstyle error
```suggestion
                        .operationPredicate((m, s, o) -> o.getId().getName(s).equals("CreateBucket")
                                && testServiceId(s))
```

**Review by trivikr — APPROVED** [review]
