### PR TITLE
fix(middleware-signing): memoize temporary credentials

### LINKED ISSUE #2107: Dynamic Credentials are Refreshed Too Often
## Describe the bug
Credentials providers are invoked every time signing a request. The credentials' `expiration` are essentially ignored. This results in too many requests to STS or IMDS. 

#### Is the issue in the browser/Node.js/ReactNative?
ALL

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.

```javascript
const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
const { STSClient, AssumeRoleCommand } = require("@aws-sdk/client-sts");

const roleArn = /**/;
const roleSessionName = "assume-role";

const sleep = (ms) =>
  new Promise((resolve) => {
    setTimeout(resolve, ms);
  });

const run = async () => {
  const client = new S3Client({
    // logger: console,
    credentials: async () => {
      const sts = new STSClient({
        /* logger: console */
      });
      const { Credentials } = await sts.send(
        new AssumeRoleCommand({
          RoleArn: roleArn,
          RoleSessionName: roleSessionName,
        })
      );
      console.log(`Successfully assume role ${roleSessionName}`);
      return {
        accessKeyId: Credentials.AccessKeyId,
        secretAccessKey: Credentials.SecretAccessKey,
        sessionToken: Credentials.SessionToken,
        expiration: Credentials.Expiration,
      };
    },
  });

  for (let i = 0; i < 5; i++) {
    const { Buckets } = await client.send(new ListBucketsCommand({}));
    console.log(`Successfull get response of ${Buckets.length} buckets.`);
    await sleep(1000);
  }
};

run();
```

#### Observed behavior
Assume role calls are made before each API call.

```console
Successfully assume role assume-role-test
Successfull get response of X buckets.
Successfully assume role assume-role-test
Successfull get response of X buckets.
Successfully assume role assume-role-test
Successfull get response of X buckets.
Successfully assume role assume-role-test
Successfull get response of X buckets.
Successfully assume role assume-role-test
Successfull get response of X buckets.
```

#### Expected behavior
Only one STS call should be made in this test case.

### PR DESCRIPTION
**Pull request by AllanZhengYP**
### Issue
Resolves #2107

### Description
It turns out not difficult to fix. When resolving the credentails in the `resolveAwsAuthConfig()`, if the user supplies a customer credential provider, the client will memoize the resolved value. If the resolved value is expired, the credential will be reloaded. If the credential provider only returns a static credential(never expires), the credential will keep memoized.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: packages/middleware-signing/src/configurations.ts [hunk 1]
```diff
@@ -81,12 +86,23 @@ export function resolveAwsAuthConfig<T>(input: T & AwsAuthInputConfig & Previous
...
   }
   return input as Provider<T>;
-}
+};
+
+const normalizeCredentialProvider = (credentials: Credentials | Provider<Credentials>): Provider<Credentials> => {
+  if (typeof credentials === "function") {
+    return memoize(
+      credentials,
+      (credentials) => credentials.expiration !== undefined && credentials.expiration.getTime() - Date.now() < 300000,
```
Comment (alexforsyth) [inline packages/middleware-signing/src/configurations.ts:103]: can we pull this magic number into a named const?

**Review by alexforsyth — APPROVED** [review]
Nits, lgtm
